name: Run MLflow Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow

      - name: Run MLflow project
        run: |
          mlflow run MLProject

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(mlflow search | head -n 2 | tail -n 1 | awk '{print $1}')
          echo "Latest run ID: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
